#!/usr/bin/env php
<?php

use Melon\Foundation\Application;

require_once __DIR__ . "/vendor/autoload.php";

/** @var Application $application */
$application = require_once __DIR__ . "/bootstrap/app.php";

/** @var App\Console\Kernel $kernel */
$kernel = $application->get(App\Console\Kernel::class);

$kernel->run();
